name: Clean Environment Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/dotnet-build-and-test.yaml@780d2001be902a9523de8331da2c77c687abbddb
    with:
      codecov-flags: ",github-action-network-test"
