name: Clean Environment Tests

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Print debug info
        run: dotnet --info

      - name: Install dependencies
        run: dotnet restore ${{ inputs.project-file }}

      - name: Build
        run: dotnet build ${{ inputs.project-file }} --no-restore

      - name: Test
        run: dotnet test ${{ inputs.project-file }} --no-restore --verbosity normal
